version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: bh0na/reverseproxy 
  backend_user:
    build:
      context: ../../restapi-user
    image: bh0na/udacity-restapi-user
  backend_feed:
    build:
      context: ../../restapi-feed  
    image: bh0na/udacity-restapi-feed
  frontend:
    build:
      context: ../../frontend  
    image: bh0na/udacity-frontend:local
